# Lab 1 - Introduction to Jupyter and Algorithmic Thinking

## Overview
This lab is designed to help you get comfortable with the **Jupyter Notebook** environment. 

The problems below serve as foundational exercises, introducing **matrix operations, lists and graphs**, which will later connect to **deep learning models**.

## Problem 1: Matrix Convolution

**Description:**
Given a matrix of **N × M** dimensions with randomly generated values, implement a **convolution algorithm** that adjusts the value of each element using a **3×3 convolution kernel**.

**Formula:**
Each element at **(i, j)** should be updated as the **average of itself and its 8 neighboring elements**.
- Ignore the boundary elements (i.e., elements on the first and last row/column should remain unchanged).



In [16]:
import numpy as np

n = 6
m = 8
matrix = np.random.randint(10, size=(n, m))
kernel = np.ones((3, 3)) / 9  

matrix_final = matrix.copy().astype(int)

for i in range(1, n - 1):
    for j in range(1, m - 1):
        patch = matrix[i-1:i+2, j-1:j+2]  
        matrix_final[i, j] = np.sum(patch * kernel)

print(matrix)
print(matrix_final)


[[8 1 1 8 4 2 0 7]
 [9 0 1 3 6 2 2 2]
 [0 3 0 0 8 7 1 5]
 [4 1 0 5 1 5 3 4]
 [2 3 6 2 4 6 5 9]
 [3 6 8 7 0 6 1 2]]
[[8 1 1 8 4 2 0 7]
 [9 2 1 3 4 3 3 2]
 [0 2 1 2 4 3 3 5]
 [4 2 2 2 4 4 5 4]
 [2 3 4 3 4 3 4 9]
 [3 6 8 7 0 6 1 2]]


## Problem 2: Prefix Sum Array
**Description:**
Given a list of **N** numbers, compute the **prefix sum array**, where each element at index `i` is the sum of all elements from index `0` to `i` in the original list.

**Example:**
```python
Input: [1, 2, 3, 4, 5]
Output: [1, 3, 6, 10, 15]
```

In [5]:
### Solve here
input = [1, 2, 3, 4, 5]

def prefix_sum(input, index) :
    return sum([input[j] for j in range(index + 1)])


output = []

for i in range(len(input)) :
    output.append(prefix_sum(input, i))
    
print(output)

[1, 3, 6, 10, 15]


## Problem 3: Finding the Longest Increasing Subsequence

**Description:**
Given an array of **N** integers, find the length of the **longest increasing subsequence** (LIS). A subsequence is a sequence that appears in the same order but is not necessarily contiguous.

**Example:**
```python
Input: [10, 9, 2, 5, 3, 7, 101, 18]
Output: 4
(Explanation: The LIS is [2, 3, 7, 101])
```

In [15]:
input = [10, 9, 2, 5, 3, 7, 101, 18]
dp = [1] * len(input)

for i in range(1, len(input)):
    for j in range(i):
        if input[j] < input[i]:
            dp[i] = max(dp[i], dp[j] + 1)
print(input)
print(dp)
print(max(dp))  

[10, 9, 2, 5, 3, 7, 101, 18]
[1, 1, 1, 2, 2, 3, 4, 4]
4


## Problem 4: Binary Search on a Sorted Array
**Description:**
Given a **sorted array** of `N` integers and a **target value**, implement a **binary search algorithm** to check if the target exists in the array.

**Example:**
```python
Input: arr = [1, 3, 5, 7, 9, 11], target = 5
Output: True
```

In [8]:
### Solve here

arr = [1, 3, 5, 7, 9, 11]
target = 2


def check_exists(arr, target) :
    left = 0
    right = len(arr)
    while left < right :
        value = (left + right) //2
        if arr[value] == target :
            return True
        if arr[value] > target :
            right-=1
        if arr[value] < target :
            left+=1
    
    return False

print(check_exists(arr, target))

False


## Problem 5: Shortest Path in an Unweighted Graph
**Description:**
Given an **undirected, unweighted graph** represented as an adjacency list, find the **shortest path** between a given start node and a target node using **Breadth-First Search (BFS)**.

**Example Graph Representation:**
```python
graph = {
    1: [2, 4],
    2: [1, 3, 5],
    3: [2, 6],
    4: [1, 5],
    5: [2, 4, 6],
    6: [3, 5]
}
```

**Example:**
```python
Input: start = 1, target = 6
Output: [1, 2, 4, 3, 5, 6]
```

In [ ]:
from collections import deque
graph = {
    1: [2, 4],
    2: [1, 3, 5],
    3: [2, 6],
    4: [1, 5],
    5: [2, 4, 6],
    6: [3, 5]
}

start = 1
target = 6
output = []

def bfs(graph, start):
    visited = set([start])
    queue = deque([start])
    
    while queue:
        node = queue.popleft()
        output.append(node)
        
        for neighbor in graph[node]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)
                
       
bfs(graph, start)       
print(output)
    




[1, 2, 4, 3, 5, 6]
